// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskFlow.WebApi.Infrastructure.Data;

#nullable disable

namespace TaskFlow.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260716114722_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskFlow.WebApi.Core.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("af49de62-068e-467e-8f17-9ba4ccf33473"),
                            Code = "taskitem.create",
                            Description = "Grup içindeki görevleri oluşturma yetkisi."
                        },
                        new
                        {
                            Id = new Guid("07a67e69-1d76-4ba4-a644-f04863a29c90"),
                            Code = "taskitem.read",
                            Description = "Grup içindeki görevleri görüntüleme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("a2a7e721-5dc3-403a-bdd5-628887602839"),
                            Code = "taskitem.update",
                            Description = "Grup içindeki görevleri güncelleme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("753469fe-c14a-4e8a-914e-786f3e78322d"),
                            Code = "taskitem.delete",
                            Description = "Grup içindeki görevleri silme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("365ccfa9-d0ce-4a7a-8e07-a7eaa4238474"),
                            Code = "taskitem.status.update",
                            Description = "Grup içindeki görevlerin durumunu güncelleme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("912c74bc-4f5c-4f1c-8753-05cfad084bfd"),
                            Code = "taskitem.deadline.update",
                            Description = "Grup içindeki görevlerin son teslim tarihini güncelleme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("5193bc28-ea67-43d7-a105-7026d2d668e3"),
                            Code = "taskitem.assign",
                            Description = "Grup içindeki görevleri atama yetkisi."
                        },
                        new
                        {
                            Id = new Guid("8c9a2c14-6516-493e-9b21-56c113a86c13"),
                            Code = "workspace.view",
                            Description = "Çalışma alanını ve genel özet ekranını görüntüleme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("02b08e56-e99f-4ef3-a99e-8ec70754194f"),
                            Code = "workspace.member.add",
                            Description = "Çalışma alanına yeni takım arkadaşı/üye davet etme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("953cd531-6149-4e63-bd5d-862f41053d32"),
                            Code = "workspace.member.remove",
                            Description = "Çalışma alanından mevcut bir üyeyi tamamen çıkarma yetkisi."
                        },
                        new
                        {
                            Id = new Guid("601059f0-0212-498f-9bf4-cdee28e4ba2c"),
                            Code = "workspace.role.assign",
                            Description = "Çalışma alanındaki üyelere rol (Admin, Member vb.) atama ve değiştirme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("6b08ed62-b54e-41b5-8f10-0e52062150df"),
                            Code = "workspace.role.create",
                            Description = "Çalışma alanına özel (Custom Role) yeni roller tanımlama yetkisi."
                        },
                        new
                        {
                            Id = new Guid("0592df3c-6b6b-4b1d-bff2-5d779755a890"),
                            Code = "workspace.role.update",
                            Description = "Çalışma alanına özel tanımlanmış rollerin yetki matrisini güncelleme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("e885fd39-00d9-4a16-b94b-bcf65b60845b"),
                            Code = "workspace.role.delete",
                            Description = "Çalışma alanına özel oluşturulmuş rolleri tamamen silme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("de5201a9-501f-4b61-9bb5-afd6e7342c1a"),
                            Code = "workspace.update",
                            Description = "Çalışma alanının ismini, açıklamasını ve kurumsal genel ayarlarını düzenleme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("1a7b0835-2203-4305-b9bc-17633440d35c"),
                            Code = "workspace.delete",
                            Description = "Çalışma alanını (Workspace) tüm verileriyle birlikte kalıcı olarak silme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("23c879f0-49ca-402a-9610-574677f4f70d"),
                            Code = "activitylog.read",
                            Description = "Activity logları görüntüleme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("93ecadf9-ce30-4843-ad61-236d39e7184b"),
                            Code = "comments.create",
                            Description = "Görevler için yorum oluşturma yetkisi."
                        },
                        new
                        {
                            Id = new Guid("11afb428-b2d3-40d3-8008-b5c7aecba8b4"),
                            Code = "comments.read",
                            Description = "Görevler için yorumları görüntüleme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("cd0c59f8-ab0f-45cc-97bc-98c6ac13344f"),
                            Code = "comments.update",
                            Description = "Görevler için yorumları güncelleme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("31e13039-cb2f-497c-8fb9-1d98d480aa96"),
                            Code = "comments.delete",
                            Description = "Görevler için yorumları silme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("6151859b-1c5c-4bd3-8202-656c02ae189d"),
                            Code = "projects.create",
                            Description = "Çalışma alanı altında yeni panolar/projeler oluşturma yetkisi."
                        },
                        new
                        {
                            Id = new Guid("66f5f8bc-a5cf-4851-8c01-79dd50cfa4b6"),
                            Code = "projects.read",
                            Description = "Mevcut projeleri, pano listelerini ve proje detaylarını görüntüleme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("f5a6d297-a279-4563-967a-f8cd37af9732"),
                            Code = "projects.update",
                            Description = "Mevcut projelerin isim, renk, kategori ve temel ayarlarını düzenleme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("d5f4d12d-1533-4143-98f3-ef0f9d4c92ed"),
                            Code = "projects.delete",
                            Description = "Bir projeyi/panoyu içindeki tüm görevlerle birlikte kalıcı olarak silme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("b1caed1d-4b83-47d2-839d-dc5a9b9b3617"),
                            Code = "attachments.create",
                            Description = "Görevler için dosya ekleme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("b0670926-df3f-41e3-a5d8-9a2cb70967e7"),
                            Code = "attachments.read",
                            Description = "Görevler için dosyaları görüntüleme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("c3e756b7-e7c8-4373-8741-a3328e5413dd"),
                            Code = "attachments.delete",
                            Description = "Görevler için dosyaları silme yetkisi."
                        },
                        new
                        {
                            Id = new Guid("ffc869ed-7030-4d5a-9eab-9957d13efe8c"),
                            Code = "attachments.update",
                            Description = "Görevler için dosyaları güncelleme yetkisi."
                        });
                });

            modelBuilder.Entity("TaskFlow.WebApi.Core.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("8c9a2c14-6516-493e-9b21-56c113a86c13")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("02b08e56-e99f-4ef3-a99e-8ec70754194f")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("953cd531-6149-4e63-bd5d-862f41053d32")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("601059f0-0212-498f-9bf4-cdee28e4ba2c")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("6b08ed62-b54e-41b5-8f10-0e52062150df")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("0592df3c-6b6b-4b1d-bff2-5d779755a890")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("de5201a9-501f-4b61-9bb5-afd6e7342c1a")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("1a7b0835-2203-4305-b9bc-17633440d35c")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("e885fd39-00d9-4a16-b94b-bcf65b60845b")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("af49de62-068e-467e-8f17-9ba4ccf33473")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("07a67e69-1d76-4ba4-a644-f04863a29c90")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("a2a7e721-5dc3-403a-bdd5-628887602839")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("753469fe-c14a-4e8a-914e-786f3e78322d")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("365ccfa9-d0ce-4a7a-8e07-a7eaa4238474")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("912c74bc-4f5c-4f1c-8753-05cfad084bfd")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("5193bc28-ea67-43d7-a105-7026d2d668e3")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("6151859b-1c5c-4bd3-8202-656c02ae189d")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("66f5f8bc-a5cf-4851-8c01-79dd50cfa4b6")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("f5a6d297-a279-4563-967a-f8cd37af9732")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("d5f4d12d-1533-4143-98f3-ef0f9d4c92ed")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("93ecadf9-ce30-4843-ad61-236d39e7184b")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("11afb428-b2d3-40d3-8008-b5c7aecba8b4")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("cd0c59f8-ab0f-45cc-97bc-98c6ac13344f")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("31e13039-cb2f-497c-8fb9-1d98d480aa96")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("b1caed1d-4b83-47d2-839d-dc5a9b9b3617")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("b0670926-df3f-41e3-a5d8-9a2cb70967e7")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("ffc869ed-7030-4d5a-9eab-9957d13efe8c")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("c3e756b7-e7c8-4373-8741-a3328e5413dd")
                        },
                        new
                        {
                            RoleId = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            PermissionId = new Guid("23c879f0-49ca-402a-9610-574677f4f70d")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("8c9a2c14-6516-493e-9b21-56c113a86c13")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("02b08e56-e99f-4ef3-a99e-8ec70754194f")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("953cd531-6149-4e63-bd5d-862f41053d32")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("601059f0-0212-498f-9bf4-cdee28e4ba2c")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("de5201a9-501f-4b61-9bb5-afd6e7342c1a")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("e885fd39-00d9-4a16-b94b-bcf65b60845b")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("6b08ed62-b54e-41b5-8f10-0e52062150df")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("0592df3c-6b6b-4b1d-bff2-5d779755a890")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("af49de62-068e-467e-8f17-9ba4ccf33473")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("07a67e69-1d76-4ba4-a644-f04863a29c90")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("a2a7e721-5dc3-403a-bdd5-628887602839")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("753469fe-c14a-4e8a-914e-786f3e78322d")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("365ccfa9-d0ce-4a7a-8e07-a7eaa4238474")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("912c74bc-4f5c-4f1c-8753-05cfad084bfd")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("5193bc28-ea67-43d7-a105-7026d2d668e3")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("6151859b-1c5c-4bd3-8202-656c02ae189d")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("66f5f8bc-a5cf-4851-8c01-79dd50cfa4b6")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("f5a6d297-a279-4563-967a-f8cd37af9732")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("d5f4d12d-1533-4143-98f3-ef0f9d4c92ed")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("93ecadf9-ce30-4843-ad61-236d39e7184b")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("11afb428-b2d3-40d3-8008-b5c7aecba8b4")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("cd0c59f8-ab0f-45cc-97bc-98c6ac13344f")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("31e13039-cb2f-497c-8fb9-1d98d480aa96")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("b1caed1d-4b83-47d2-839d-dc5a9b9b3617")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("b0670926-df3f-41e3-a5d8-9a2cb70967e7")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("ffc869ed-7030-4d5a-9eab-9957d13efe8c")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("c3e756b7-e7c8-4373-8741-a3328e5413dd")
                        },
                        new
                        {
                            RoleId = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            PermissionId = new Guid("23c879f0-49ca-402a-9610-574677f4f70d")
                        },
                        new
                        {
                            RoleId = new Guid("ecb6c928-cc9b-404d-b04b-a9612c377cce"),
                            PermissionId = new Guid("8c9a2c14-6516-493e-9b21-56c113a86c13")
                        },
                        new
                        {
                            RoleId = new Guid("ecb6c928-cc9b-404d-b04b-a9612c377cce"),
                            PermissionId = new Guid("af49de62-068e-467e-8f17-9ba4ccf33473")
                        },
                        new
                        {
                            RoleId = new Guid("ecb6c928-cc9b-404d-b04b-a9612c377cce"),
                            PermissionId = new Guid("07a67e69-1d76-4ba4-a644-f04863a29c90")
                        },
                        new
                        {
                            RoleId = new Guid("ecb6c928-cc9b-404d-b04b-a9612c377cce"),
                            PermissionId = new Guid("a2a7e721-5dc3-403a-bdd5-628887602839")
                        },
                        new
                        {
                            RoleId = new Guid("ecb6c928-cc9b-404d-b04b-a9612c377cce"),
                            PermissionId = new Guid("365ccfa9-d0ce-4a7a-8e07-a7eaa4238474")
                        },
                        new
                        {
                            RoleId = new Guid("ecb6c928-cc9b-404d-b04b-a9612c377cce"),
                            PermissionId = new Guid("5193bc28-ea67-43d7-a105-7026d2d668e3")
                        },
                        new
                        {
                            RoleId = new Guid("ecb6c928-cc9b-404d-b04b-a9612c377cce"),
                            PermissionId = new Guid("66f5f8bc-a5cf-4851-8c01-79dd50cfa4b6")
                        },
                        new
                        {
                            RoleId = new Guid("ecb6c928-cc9b-404d-b04b-a9612c377cce"),
                            PermissionId = new Guid("93ecadf9-ce30-4843-ad61-236d39e7184b")
                        },
                        new
                        {
                            RoleId = new Guid("ecb6c928-cc9b-404d-b04b-a9612c377cce"),
                            PermissionId = new Guid("11afb428-b2d3-40d3-8008-b5c7aecba8b4")
                        },
                        new
                        {
                            RoleId = new Guid("ecb6c928-cc9b-404d-b04b-a9612c377cce"),
                            PermissionId = new Guid("cd0c59f8-ab0f-45cc-97bc-98c6ac13344f")
                        },
                        new
                        {
                            RoleId = new Guid("ecb6c928-cc9b-404d-b04b-a9612c377cce"),
                            PermissionId = new Guid("b1caed1d-4b83-47d2-839d-dc5a9b9b3617")
                        },
                        new
                        {
                            RoleId = new Guid("ecb6c928-cc9b-404d-b04b-a9612c377cce"),
                            PermissionId = new Guid("b0670926-df3f-41e3-a5d8-9a2cb70967e7")
                        },
                        new
                        {
                            RoleId = new Guid("ecb6c928-cc9b-404d-b04b-a9612c377cce"),
                            PermissionId = new Guid("ffc869ed-7030-4d5a-9eab-9957d13efe8c")
                        },
                        new
                        {
                            RoleId = new Guid("d191a4b1-1ce3-43ed-8efa-3439ce5d6a9c"),
                            PermissionId = new Guid("8c9a2c14-6516-493e-9b21-56c113a86c13")
                        },
                        new
                        {
                            RoleId = new Guid("d191a4b1-1ce3-43ed-8efa-3439ce5d6a9c"),
                            PermissionId = new Guid("07a67e69-1d76-4ba4-a644-f04863a29c90")
                        },
                        new
                        {
                            RoleId = new Guid("d191a4b1-1ce3-43ed-8efa-3439ce5d6a9c"),
                            PermissionId = new Guid("66f5f8bc-a5cf-4851-8c01-79dd50cfa4b6")
                        },
                        new
                        {
                            RoleId = new Guid("d191a4b1-1ce3-43ed-8efa-3439ce5d6a9c"),
                            PermissionId = new Guid("11afb428-b2d3-40d3-8008-b5c7aecba8b4")
                        },
                        new
                        {
                            RoleId = new Guid("d191a4b1-1ce3-43ed-8efa-3439ce5d6a9c"),
                            PermissionId = new Guid("b0670926-df3f-41e3-a5d8-9a2cb70967e7")
                        });
                });

            modelBuilder.Entity("TaskFlow.WebApi.Core.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("TaskFlow.WebApi.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TaskFlow.WebApi.Core.Entities.UserWorkspaceRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId", "WorkspaceId");

                    b.HasIndex("RoleId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("UserWorkspaceRoles");
                });

            modelBuilder.Entity("TaskFlow.WebApi.Core.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPersonal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("SpaceDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SpaceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("TaskFlow.WebApi.Core.Entities.WorkspaceRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"WorkspaceId\" IS NULL");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique()
                        .HasFilter("\"WorkspaceId\" IS NOT NULL");

                    b.ToTable("WorkspaceRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("87f54898-67b8-42c9-b3bf-df33cd1d0c6a"),
                            Name = "Owner"
                        },
                        new
                        {
                            Id = new Guid("c89567a9-7c63-4c62-80de-dd54fc3a1c9e"),
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("ecb6c928-cc9b-404d-b04b-a9612c377cce"),
                            Name = "Member"
                        },
                        new
                        {
                            Id = new Guid("d191a4b1-1ce3-43ed-8efa-3439ce5d6a9c"),
                            Name = "Viewer"
                        });
                });

            modelBuilder.Entity("TaskFlow.WebApi.Core.Entities.RolePermission", b =>
                {
                    b.HasOne("TaskFlow.WebApi.Core.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskFlow.WebApi.Core.Entities.WorkspaceRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TaskFlow.WebApi.Core.Entities.TaskItem", b =>
                {
                    b.HasOne("TaskFlow.WebApi.Core.Entities.User", "AssignedUser")
                        .WithMany("AssignedTaskItems")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaskFlow.WebApi.Core.Entities.Workspace", "Workspace")
                        .WithMany("TaskItems")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TaskFlow.WebApi.Core.Entities.UserWorkspaceRole", b =>
                {
                    b.HasOne("TaskFlow.WebApi.Core.Entities.WorkspaceRole", "Role")
                        .WithMany("UserWorkspaceRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskFlow.WebApi.Core.Entities.User", "User")
                        .WithMany("UserWorkspaceRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskFlow.WebApi.Core.Entities.Workspace", "Workspace")
                        .WithMany("UserWorkspaceRoles")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TaskFlow.WebApi.Core.Entities.WorkspaceRole", b =>
                {
                    b.HasOne("TaskFlow.WebApi.Core.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TaskFlow.WebApi.Core.Entities.User", b =>
                {
                    b.Navigation("AssignedTaskItems");

                    b.Navigation("UserWorkspaceRoles");
                });

            modelBuilder.Entity("TaskFlow.WebApi.Core.Entities.Workspace", b =>
                {
                    b.Navigation("TaskItems");

                    b.Navigation("UserWorkspaceRoles");
                });

            modelBuilder.Entity("TaskFlow.WebApi.Core.Entities.WorkspaceRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserWorkspaceRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
